# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: charts
#   namespace: argocd
# spec:
#   goTemplate: true
#   generators:
#     - git:
#         repoURL: https://github.com/dustjs159/gitops-local-test.git
#         revision: master
#         directories:
#           - path: charts/harbor 
#   template:
#     metadata:
#       name: '{{.path.basename}}'  # harbor
#     spec:
#       project: default
#       sources:
#         # Harbor Helm Chart
#         - chart: harbor
#           repoURL: https://helm.goharbor.io
#           targetRevision: 1.17.0  # 차트 버전
#           helm:
#             valueFiles:
#               - $values/charts/harbor/values.yaml
#         # Git repo (values)
#         - repoURL: https://github.com/dustjs159/gitops-local-test.git
#           targetRevision: master
#           ref: values
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: harbor
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
#         syncOptions:
#           - CreateNamespace=true
#           - ServerSideApply=true